version: "3.8"
services:
  reading-service:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: dev # Активируем профиль dev
      DB_HOST: database # Имя хоста базы данных в Docker Compose
      DB_PORT: 5432 # Порт базы данных
      DB_NAME: reading_db # Имя базы данных
      DB_USERNAME_FILE: /run/secrets/db_username # Путь к секрету с именем пользователя
      DB_PASSWORD_FILE: /run/secrets/db_password # Путь к секрету с паролем
    secrets:
      - db_username
      - db_password
    ports:
      - "8080:8080" # Пробрасываем порт приложения
    depends_on:
      - database # Запускаем приложение только после базы данных

  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres # Имя пользователя базы данных
      POSTGRES_PASSWORD: postgres # Пароль базы данных
      POSTGRES_DB: reading_db # Имя базы данных
    ports:
      - "5432:5432" # Пробрасываем порт базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data # Хранение данных в volume

secrets:
  db_username:
    file: ./secrets/db_username.txt # Секрет с именем пользователя
  db_password:
    file: ./secrets/db_password.txt # Секрет с паролем

volumes:
  postgres_data:
