name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Шаг 3: Извлечение версии из POM файла
      - name: Extract version from POM
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Шаг 4: Сборка JAR файла
      - name: Build JAR file
        run: mvn clean package -DskipTests

      # Шаг 5: Аутентификация в Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Шаг 6: Настройка Docker для Google Cloud
      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      # Шаг 7: Сборка и загрузка Docker-образа в Google Container Registry (GCR)
      - name: Build, tag, and push Docker image
        run: |
          IMAGE_TAG=${{ env.VERSION }}
          IMAGE_URI=gcr.io/ieltsdemo-447009/reading-service:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Шаг 8: Деплой в Google Cloud Run с использованием секретов
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: reading-service
          image: ${{ env.IMAGE_URI }}
          region: us-central1
          allow-unauthenticated: true
          set-secrets: |
            DB_PASSWORD=DB_PASSWORD:latest
            DB_HOST=DB_HOST:latest
            DB_USER=DB_USER:latest
            DB_NAME=DB_NAME:latest
            DB_PORT=DB_PORT:latest
            GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest
            APP_REDIRECT_URI=APP_REDIRECT_URI:latest
            GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest
            SPRING_PROFILES_ACTIVE=SPRING_PROFILES_ACTIVE:latest
