name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Установить Java 21 (для сборки JAR)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Сборка JAR-файла
      - name: Build JAR file
        run: mvn clean package -DskipTests

      # Логин в Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: "AKIAEXAMPLEACCESSKEY"
          AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          AWS_REGION: us-east-1

      # Сборка и загрузка Docker-образа в Amazon ECR
      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: "438465153597.dkr.ecr.us-east-1.amazonaws.com"
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          IMAGE_URI=438465153597.dkr.ecr.us-east-1.amazonaws.com/reading-service:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Регистрация новой ECS Task Definition
      - name: Register ECS Task Definition
        run: |
          FAMILY_NAME=reading-service-task
          TASK_DEFINITION=$(cat <<EOF
          {
            "family": "$FAMILY_NAME",
            "containerDefinitions": [
              {
                "name": "reading-service",
                "image": "$IMAGE_URI",
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 8080,
                    "protocol": "tcp"
                  }
                ]
              }
            ]
          }
          EOF
          )
          echo "$TASK_DEFINITION" > task-def.json
          aws ecs register-task-definition \
            --cli-input-json file://task-def.json \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: "AKIAEXAMPLEACCESSKEY"
          AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          AWS_REGION: us-east-1

      # Развертывание на ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: "ieltsdemo-cluster"  # Имя вашего ECS-кластера
          service: "reading-service"  # Имя вашего ECS-сервиса
          task-definition: "reading-service-task"  # Имя Task Definition
          wait-for-service-stability: true
        env:
          AWS_ACCESS_KEY_ID: "AKIAEXAMPLEACCESSKEY"
          AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          AWS_REGION: us-east-1
