name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Установить Java 21 (для сборки JAR)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Извлечение версии из POM файла
      - name: Extract version from POM
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Сборка JAR-файла
      - name: Build JAR file
        run: mvn clean package -DskipTests

      # Аутентификация в Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Настройка Docker для Google Cloud
      - name: Configure Docker for Google Cloud
        run: |
          gcloud auth configure-docker

      # Сборка и загрузка Docker-образа в Google Container Registry (GCR)
      - name: Build, tag, and push Docker image
        run: |
          IMAGE_TAG=${{ env.VERSION }}
          IMAGE_URI=gcr.io/ieltsdemo-447009/reading-service:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Деплой в Google Cloud Run
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: reading-service
          image: ${{ env.IMAGE_URI }}
          region: us-central1
          allow-unauthenticated: true
