name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Установить Java 21 (для сборки JAR)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Сборка JAR-файла
      - name: Build JAR file
        run: mvn clean package -DskipTests

      # Логин в Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'private'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      # Сборка и загрузка Docker-образа в Amazon ECR
      - name: Build, tag, and push Docker image
        env:
          AWS_REGION: us-east-1
          ECR_REGISTRY: 438465153597.dkr.ecr.us-east-1.amazonaws.com
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          IMAGE_URI=438465153597.dkr.ecr.us-east-1.amazonaws.com/reading-service:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Update Task Definition
        run: |
          FAMILY_NAME=reading-service-task
          IMAGE_URI=438465153597.dkr.ecr.us-east-1.amazonaws.com/reading-service:$(git rev-parse --short HEAD)

          # Получение текущего Task Definition без лишних полей
          TASK_DEFINITION=$(aws ecs describe-task-definition \
            --task-definition $FAMILY_NAME \
            --query "taskDefinition" \
            --output json | \
            jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredBy, .registeredAt)')
          
          # Обновление Docker-образа в Task Definition
          UPDATED_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE_URI $IMAGE_URI '.containerDefinitions[0].image=$IMAGE_URI')
          
          echo $UPDATED_TASK_DEFINITION > task-def.json

          # Регистрация обновленного Task Definition
          aws ecs register-task-definition \
            --cli-input-json file://task-def.json \
            --region us-east-1
          
          # Получение последней ревизии Task Definition
          TASK_REVISION=$(aws ecs describe-task-definition \
            --task-definition $FAMILY_NAME \
            --query "taskDefinition.revision" \
            --output text)

          # Обновление ECS-сервиса
          aws ecs update-service \
            --cluster ieltsdemo-cluster \
            --service ielts-reading-service \
            --task-definition $FAMILY_NAME:$TASK_REVISION \
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
